[package]
name = "chonk-arm"
version = "0.0.0"
edition = "2021"

[dependencies]
chonk-arm-proc = { path = "../chonk-arm-proc" }
proc-bitfield = "0.2"
strum = { version = "0.25", features = ["derive"] }
